#!/usr/bin/env bash
sed -i 's|C1.telerama.fr|TF1.fr|' "/root/euroiptv.xml"
sed -i 's|C2.telerama.fr|France2.fr|' "/root/euroiptv.xml"
sed -i 's|C3.telerama.fr|France3.fr|' "/root/euroiptv.xml"
sed -i 's|C4.telerama.fr|CANALplus.fr|' "/root/euroiptv.xml"
sed -i 's|C5.telerama.fr|France5.fr|' "/root/euroiptv.xml"
sed -i 's|C6.telerama.fr|M6.fr|' "/root/euroiptv.xml"
sed -i 's|C7.telerama.fr|ARTE.fr|' "/root/euroiptv.xml"
sed -i 's|C8.telerama.fr|C8.fr|' "/root/euroiptv.xml"
sed -i 's|C9.telerama.fr|W9.fr|' "/root/euroiptv.xml"
sed -i 's|C10.telerama.fr|TMC.fr|' "/root/euroiptv.xml"
sed -i 's|C11.telerama.fr|NT1.fr|' "/root/euroiptv.xml"
sed -i 's|C12.telerama.fr|NRJ12.fr|' "/root/euroiptv.xml"
sed -i 's|C14.telerama.fr|LCP.fr|' "/root/euroiptv.xml"
sed -i 's|C13.telerama.fr|France4.fr|' "/root/euroiptv.xml"
sed -i 's|C15.telerama.fr|BFMTV.fr|' "/root/euroiptv.xml"
sed -i 's|C16.telerama.fr|CNews.fr|' "/root/euroiptv.xml"
sed -i 's|C17.telerama.fr|CStar.fr|' "/root/euroiptv.xml"
sed -i 's|C18.telerama.fr|Gulli.fr|' "/root/euroiptv.xml"
sed -i 's|C119.telerama.fr|FranceO.fr|' "/root/euroiptv.xml"
sed -i 's|C4131.telerama.fr|HD1.fr|' "/root/euroiptv.xml"
sed -i 's|C4132.telerama.fr|Equipe21.fr|' "/root/euroiptv.xml"
sed -i 's|C4133.telerama.fr|6ter.fr|' "/root/euroiptv.xml"
sed -i 's|C4134.telerama.fr|Numero23.fr|' "/root/euroiptv.xml"
sed -i 's|C4135.telerama.fr|RMCdecouverte.fr|' "/root/euroiptv.xml"
sed -i 's|C4136.telerama.fr|Cherie25.fr|' "/root/euroiptv.xml"
sed -i 's|C133.telerama.fr|LCI.fr|' "/root/euroiptv.xml"
sed -i 's|C2111.telerama.fr|Franceinfo.fr|' "/root/euroiptv.xml"
sed -i 's|C227.telerama.fr|Teva.fr|' "/root/euroiptv.xml"
sed -i 's|C23.telerama.fr|AB1|' "/root/euroiptv.xml"
sed -i 's|C24.telerama.fr|AB3|' "/root/euroiptv.xml"
sed -i 's|C199.telerama.fr|RTL9|' "/root/euroiptv.xml"
sed -i 's|C186.telerama.fr|PARIS PREMIERE|' "/root/euroiptv.xml"
sed -i 's|C242.telerama.fr|TV8 Mont Blanc|' "/root/euroiptv.xml"
sed -i 's|C243.telerama.fr|TV Breizh|' "/root/euroiptv.xml"
sed -i 's|C43.telerama.fr|Canal+ Cinema|' "/root/euroiptv.xml"
sed -i 's|C4138.telerama.fr|Canal+ Series|' "/root/euroiptv.xml"
sed -i 's|C45.telerama.fr|Canal+ Family|' "/root/euroiptv.xml"
sed -i 's|C44.telerama.fr|Canal+ Decale|' "/root/euroiptv.xml"
sed -i 's|C62.telerama.fr|Cine+ Premier|' "/root/euroiptv.xml"
sed -i 's|C61.telerama.fr|Cine+ Frisson|' "/root/euroiptv.xml"
sed -i 's|C60.telerama.fr|Cine+ Famiz|' "/root/euroiptv.xml"
sed -i 's|C59.telerama.fr|Cine+ Emotion|' "/root/euroiptv.xml"
sed -i 's|C56.telerama.fr|Cine+ Classic|' "/root/euroiptv.xml"
sed -i 's|C203.telerama.fr|serieclub FR|' "/root/euroiptv.xml"
sed -i 's|C183.telerama.fr|OCS Max FR|' "/root/euroiptv.xml"
sed -i 's|C181.telerama.fr|OCS Choc FR|' "/root/euroiptv.xml"
sed -i 's|C206.telerama.fr|TCM Cinema FR|' "/root/euroiptv.xml"
sed -i 's|C20.telerama.fr|13eme Rue|' "/root/euroiptv.xml"
sed -i 's|C4141.telerama.fr|Paramount Channel FR|' "/root/euroiptv.xml"
sed -i 's|C202.telerama.fr|Seasons FR|' "/root/euroiptv.xml"
sed -i 's|C80.telerama.fr|E! FR|' "/root/euroiptv.xml"
sed -i 's|C248.telerama.fr|Voyage HD FR|' "/root/euroiptv.xml"
sed -i 's|C122.telerama.fr|Histoire FR|' "/root/euroiptv.xml"
sed -i 's|C29.telerama.fr|Animaux FR|' "/root/euroiptv.xml"
sed -i 's|C229.telerama.fr|TIJI FR|' "/root/euroiptv.xml"
sed -i 's|C121.telerama.fr|Game One FR|' "/root/euroiptv.xml"
sed -i 's|C142.telerama.fr|Mangas FR|' "/root/euroiptv.xml"
sed -i 's|C924.telerama.fr|Boing FR|' "/root/euroiptv.xml"
sed -i 's|C194.telerama.fr|Disney Junior FR|' "/root/euroiptv.xml"
sed -i 's|C73.telerama.fr|Disney Channel FR_2|' "/root/euroiptv.xml"
sed -i 's|C139.telerama.fr|M6 Music FR|' "/root/euroiptv.xml"
sed -i 's|C163.telerama.fr|MTV HITS FR|' "/root/euroiptv.xml"
sed -i 's|C171.telerama.fr|Nickelodeon Junior FR|' "/root/euroiptv.xml"
sed -i 's|C47.telerama.fr|CanalPlus Sport FR|' "/root/euroiptv.xml"
sed -i 's|C2095.telerama.fr|SFR Sport 1 HD FR|' "/root/euroiptv.xml"
sed -i 's|C4139.telerama.fr|beIN SPORTS 1 FR|' "/root/euroiptv.xml"
sed -i 's|C4140.telerama.fr|beIN SPORTS 2 FR|' "/root/euroiptv.xml"
sed -i 's|C4141.telerama.fr|beIN SPORTS 3 FR' "/root/euroiptv.xml"
sed -i 's|C235.telerama.fr|RTS Deux|' "/root/euroiptv.xml"
sed -i 's|C236.telerama.fr|RTS Un|' "/root/euroiptv.xml"
sed -i 's|C2095.telerama.fr|SFR Sport 1 HD FR|' "/root/euroiptv.xml"
sed -i 's|C675.telerama.fr|SFR Sport 2 HD FR|' "/root/euroiptv.xml"
